version: '3.7'
services: 
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: reverse-proxy
    ports:
      - 80:80
      - 443:443
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./certs:/etc/nginx/certs
    networks: 
      - nginx-proxy
networks:
  nginx-proxy:
    external: true