version: '3.7'
services: 
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine 
    container_name: reverse-proxy
    ports:
      - 80:80
      - 443:443
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    networks: 
      - web
networks:
  web:
    external: true